### ISSUE TITLE
fix simulation

### ISSUE THREAD

**Issue by yakobi99** [RoboticSpaceExploration/protobot#148]

**Comment by bretwitt** [comment]
Delete outdated URDF camera links (everything other than track_cam_link, depth_cam_link)

Realsense manager spawns optical & misc frames as children of the track_cam_link and depth_cam_link links, so we need a script that does the same only when we launch the simulation. I recommend loading a simulation parameter on the parameter server when you launch description, however there's probably other ways to do it as well

Some nodes also pull from the outdated camera ns rather than track_cam & depth_cam
